theme:
  name: material

site_name: CLoud Architecture Portal

plugins:
  - awesome-pages
  - multirepo:
      cleanup: false
      repos:
        - section: refarch-001
          section_path: reference-architectures
          import_url: "https://github.com/clap-demo/refarch-001
